language: ruby
cache: bundler
env:
  global:
    - TRAVIS=true
  matrix:
    - TASK=rspec
#cache: bundler # <= only for private repos on travis, it turns out
bundler_args: --without production
before_install:
  - sudo apt-get install libicu-dev -y
rvm:
  - 2.1.0
services:

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - "cp config/database.yml.travis config/database.yml"
  - "bin/rake db:create"
  - "bin/rake db:schema:load"
  - "bin/rake db:test:prepare" # shouldn't need this in 4.1 but doesn't work sometimes
script: "bin/$TASK -f d"
notifications:
  email:
    - kvirani@lighthouselabs.ca
