# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  mandrill_username: Your_Username
  mandrill_apikey: Your_API_Key
  secret_key_base: e32fd31413bfb5dda8976cc534bd09b464979aec02565da386619a441adbda6e4704f2bdc05467135891e69b55fb79290beb0c46c9c47108200f9a3e7c27e26c

test:
  secret_key_base: ce899043c698881f880cb73f75ba484dfe981dae082ddf067d37138864a257d416ff6a4fefdab9f1de5a78caf27821a0ff744bfbadcd9be7db15a6abedb551c0

staging:
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  secret_key_base: 54d244a8e1f81ee6e19a602b22114f3036982fd88cc40e035812fdeca835934e763b0c7f01fe9ff93f7c0279754606912237c14ed448101d73102a0dec89da74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
